# Generated by Django 5.1.5 on 2026-02-13 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0008_testmatch_player_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round2Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('matches_played', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('bot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='poker.bot')),
            ],
        ),
    ]
